# Generated by Django 3.1.3 on 2020-11-20 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='work',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('work', models.CharField(max_length=255)),
                ('span', models.CharField(max_length=255)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('skill', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('sno', models.IntegerField(primary_key=True, serialize=False)),
                ('profile_pic', models.ImageField(default='profile-logo.png', upload_to='')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('name', models.CharField(max_length=255)),
                ('desc', models.TextField(default="Hey There! I'm using CLGin")),
                ('linkedin', models.URLField(blank=True)),
                ('fb', models.URLField(blank=True)),
                ('ig', models.URLField(blank=True)),
                ('phone', models.IntegerField(blank=True, default=9999999999, max_length=13)),
                ('is_phone', models.BooleanField(blank=True, default=0)),
                ('year', models.CharField(default='FE', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('notification', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=255)),
                ('span', models.CharField(max_length=255)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='achievement',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('achievement', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
